# Main workflow to build project
name: Xcode Tests
on: [pull_request, workflow_dispatch]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Run tests
        run: xcodebuild test -scheme CoffeeTracker -project CoffeeTracker/CoffeeTracker.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.1' RevenueCatKey=${{secrets.RevenueCatAPI}} GitHubAPI=${{secrets.GitHubAPI}} PostHogKey=${{secrets.POSTHOGKEY}}
